AWSTemplateFormatVersion: '2010-09-09'
Description: TG Template Webapp - API Gateway

Parameters:
  NamePrefix:
    Type: String
  Environment:
    Type: String
  LambdaArn:
    Type: String
  AuthorizerLambdaArn:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${NamePrefix}-api-${Environment}
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Auth-Provider
        MaxAge: 86400

  # Lambda Authorizer
  Authorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref ApiGateway
      AuthorizerType: REQUEST
      AuthorizerUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerLambdaArn}/invocations
      AuthorizerPayloadFormatVersion: '2.0'
      AuthorizerResultTtlInSeconds: 300
      IdentitySource:
        - $request.header.Authorization
        - $request.header.x-auth-provider
      Name: JwtAuthorizer

  # Lambda Integration
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref LambdaArn
      PayloadFormatVersion: '2.0'

  # Routes
  HealthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/health
      Target: !Sub integrations/${LambdaIntegration}

  AuthTokenRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: POST /api/auth/token
      Target: !Sub integrations/${LambdaIntegration}

  AuthUserinfoRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/auth/userinfo
      Target: !Sub integrations/${LambdaIntegration}

  AuthMeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/auth/me
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Target: !Sub integrations/${LambdaIntegration}

  DashboardStatsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/dashboard/stats
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Target: !Sub integrations/${LambdaIntegration}

  TestGuidelinesListRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/test-guidelines
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Target: !Sub integrations/${LambdaIntegration}

  TestGuidelinesGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/test-guidelines/{id}
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Target: !Sub integrations/${LambdaIntegration}

  # Default Stage
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: $default
      AutoDeploy: true

  # Lambda Permission
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*

  AuthorizerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AuthorizerLambdaArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*

Outputs:
  ApiEndpoint:
    Value: !GetAtt ApiGateway.ApiEndpoint
  ApiId:
    Value: !Ref ApiGateway
